### ISSUE TITLE
figure_5.R

### ISSUE THREAD

**Issue by penglbio** [hzi-bifo/BarleyMeta#1]
Can't repeat your result.

I run the figure_5.R aggain use you data, but get the different result compared with your figure5 in the paper. my result is follow: some node color is different. Mine is blue, but yours is green in the paper.

**Comment by garridoo** [comment]
Hello,
consider that you might be using a different color palette or transparencies if you load newer versions of the plotting libraries or if you run this script manually. In any case, you can easily change the colors if you adapt these scripts to your own dataset.

**Comment by penglbio** [comment]
I just used your data and script to do the test. But get the different result.

**Comment by penglbio** [comment]
I read the code. Maybe you are right.color palette may be different

**Comment by garridoo** [comment]
I am glad to hear that and wish you good luck with your analysis.

**Comment by penglbio** [comment]
Thank you, I changed the code. Then color palette will do not influence  the result.
